      subroutine test_RR_%(isec)d_%(jsec)d_%(c3p)d_%(d3p)d(iunit,x0)
      implicit none
      INCLUDE 'coupl.inc'
      INCLUDE 'math.inc'
      INCLUDE 'nexternal.inc'
      INCLUDE 'input.inc'
      INCLUDE 'run.inc'
      INCLUDE 'cuts.inc'
      integer iunit,ievnt
      INTEGER, PARAMETER :: MXDIM = 30
      double precision x0(mxdim)
      character*10 dash10
      save ievnt
      double precision xsave(5)
      common/cxsave/xsave
      double precision e(5),l(5)
      integer i

c
      dash10='----------'
      ievnt=ievnt+1
c
      write(iunit,*)dash10//dash10//dash10//dash10
      write(iunit,*)dash10//dash10//dash10//dash10
      write(iunit,*)' EVENT NUMBER ',ievnt
      write(iunit,*)dash10//dash10//dash10//dash10
      write(iunit,*)dash10//dash10//dash10//dash10
%(limit_str)s
c
c     reinstate original xsave after testing
      do i=1,5
         xsave(i)=x0(i)
      enddo
c
      write(iunit,*)
      write(iunit,*)
      write(iunit,*)
c
      return
      end


      subroutine do_limit_RR_%(isec)d_%(jsec)d_%(c3p)d_%(d3p)d(iunit,limstr,x0,e,l)
      USE SECTORS4_MODULE
      implicit none
      INCLUDE 'coupl.inc'
      INCLUDE 'math.inc'
      INCLUDE 'nexternal.inc'
      INCLUDE 'input.inc'
      INCLUDE 'run.inc'
      INCLUDE 'cuts.inc'
      integer iitn,i,j,maxitn,iunit,ierr
      integer isec,jsec,ksec,lsec,iref
      common/cpartindices/isec,jsec,ksec,lsec,iref
      integer asec,bsec,csec,dsec
      common/csecindices/asec,bsec,csec,dsec
      integer iS1,iB1,iA1,iU1,iS2,iB2,iA2,iU2
      common/cNNLOmaplabels/iU1,iS1,iB1,iA1,iU2,iS2,iB2,iA2
C      common/cnlomaplabels/iU,iS,iB,iA,iref
      integer, parameter :: mxdim=30
      parameter(maxitn=12)
      double precision x0(mxdim),x(mxdim)
      double precision sNNLO(nexternal,nexternal)
      double precision sNLO(nexternal-1,nexternal-1)
      double precision sLO(nexternal-2,nexternal-2)
      double precision KNNLO
      double precision lam,lim,RNNLO,double_real
      character*5 str5
      character*8 limstr
      character*10 str10
      double precision p(0:3,nexternal)
      double precision pb(0:3,nexternal-1)
      double precision ptilde(0:3,nexternal-2)
      double precision xjac,xjacB,xjacCS1
      double precision xsave(5)
      DOUBLE PRECISION ANS(0:1) !TODO SET CORRECTLY RANGE OF ANS
      DOUBLE PRECISION ALPHAS, ALPHA_QCD
c      DOUBLE PRECISION W_NNLO
      DOUBLE PRECISION WGT,WGTPL,wgt_chan
      DOUBLE PRECISION SCM
      INTEGER, PARAMETER :: HEL=-1
      integer %(NNLO_proc_str)sfl_factor
      common/%(NNLO_proc_str)sflavour_factor/%(NNLO_proc_str)sfl_factor
      DOUBLE PRECISION ALPHAZ
      PARAMETER(ALPHAZ=2D0)
      common/cxsave/xsave
      double precision e(5),l(5)
      double precision K1,K2,K12
      integer real_leg_pdgs(nexternal-1),Born_leg_pdgs(nexternal-2)
      common/c_NNLO_U_PDGs/real_leg_pdgs,Born_leg_pdgs
      integer real_mapped_labels(nexternal),Born_mapped_labels(nexternal-1)
      common/c_NNLO_mapped_labels/real_mapped_labels,Born_mapped_labels

      ALPHAS=ALPHA_QCD(AS,NLOOP,MU_R)
      SCM = (2D0*EBEAM(1))**2
c
c     initialise
      x=x0
      str5 ='     '
      str10='          '
      xjac=0d0
      sNNLO=0d0
      sNLO=0d0
      sLO=0d0
      W_NNLO=0d0
      wgt_chan=1d0
c
c     TODO: MAP SOFT LIMIT AS (ilm), I.E. ONE MAPPING PER DIPOLE
c
c     start testing
      write(iunit,*)
      write(iunit,*)
      write(iunit,*)'LIM = '//trim(limstr)
      write(iunit,*)str10//'lambda'//str10//str10//'RR'//str10//str10//str5//'LIM'//str10//str10//'|RR-LIM|/|LIM|'
c
c     possibility to set by hand the starting point
c     for the limiting procedure
c      x0(1)=0.5d0
c      x0(2)=0.5d0
c
c     loop to get closer and closer to the limit
      do iitn=1,maxitn
         lam=10d0**(1d0-iitn)
c
c     initialise
         KNNLO=0d0
c
c     rescale relevant x random numbers
c       (zCS', yCS') parameterises the second radiation
c       in terms of the NLO phase space
c       They are generated by x(1), x(2), respectively

c       (zCS, yCS) parameterises the first radiation
c       in terms of the LO phase space
c       They are generated by x(4), x(5), respectively

c     TODO: this rescaling is specific for (ijr) mapping; generalise
         x(1)=abs(l(1)-x0(1)*lam**e(1))
         x(2)=abs(l(2)-x0(2)*lam**e(2))
         x(4)=abs(l(4)-x0(4)*lam**e(4))
         x(5)=abs(l(5)-x0(5)*lam**e(5))


c
c     set xsave so that the counterterms will be called with
c     more and more singular kinematics
         do i=1,5
            xsave(i)=x(i)
         enddo
c
c     recompute momenta after rescaling
         call phase_space_npt(x,sCM,iU1,iS1,iB1,iA1,iU2,iS2,iB2,iA2,p,pb,ptilde,xjac,xjacB,xjacCS1)
         if(xjac.eq.0d0.or.xjacB.eq.0d0 .or. xjacCS1 .eq. 0d0) cycle
         call invariants_from_p(p,nexternal,sNNLO,ierr)
         if(ierr.eq.1)cycle
         call invariants_from_p(pb,nexternal-1,sNLO,ierr)
         if(ierr.eq.1)cycle
         call invariants_from_p(ptilde,nexternal-2,sLO,ierr)
         if(ierr.eq.1)cycle
c
c     double real
         call %(NNLO_proc_str)sME_ACCESSOR_HOOK(P,HEL,ALPHAS,ANS)
         RNNLO = ANS(0) * %(NNLO_proc_str)sfl_factor
         if(RNNLO.lt.0d0.or.abs(RNNLO).ge.huge(1d0).or.isnan(RNNLO))cycle

         call get_sigNNLO(SNNLO,alphaz,nexternal)
         call get_W_NNLO(asec,bsec,csec,dsec)

         if(ierr.eq.1)cycle
c
c     counterterm
         call local_counter_NNLO_%(isec)d_%(jsec)d_%(c3p)d_%(d3p)d(sNNLO,p,sNLO,pb,sLO,ptilde,wgt,xjac,xjacB,x,KNNLO,wgt_chan,ierr)
         if(ierr.eq.1)cycle

         lim=KNNLO
         double_real=RNNLO*W_NNLO*xjac

         if(abs(lim).gt.0d0)then
            write(iunit,*)lam,double_real,lim,abs(double_real-lim)/abs(lim)
         else
            write(iunit,*)lam,double_real,lim,double_real,' *** '
         endif
      enddo
      x=x0
c
      return
      end
