      SUBROUTINE CONFIGS_DUMMY
      IMPLICIT NONE

      RETURN
      END

      SUBROUTINE PROPS_DUMMY
      IMPLICIT NONE

      RETURN
      END

      SUBROUTINE GETLESHOUCHE_DUMMY
      IMPLICIT NONE
      
      RETURN
      END

      SUBROUTINE DUMMY_ME_ACCESSOR_HOOK(P,HEL,USER_ALPHAS,ANS)
      IMPLICIT NONE    
      INCLUDE 'nexternal.inc'
      INTEGER I
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=10)  
      REAL*8 ANS(0:NSQAMPSO)
      REAL*8 AMP(0:NSQAMPSO)
      INTEGER HEL
      DOUBLE PRECISION USER_ALPHAS
     
      DO I=1:NSQAMPSO
         AMP(I) = 1d0
      ENDDO

      RETURN
      END
